tf_main:
    resource: "@TFMainBundle/Resources/config/routing.yml"
    prefix:   /main

login:
    path: /login
    defaults:
        _controller: TFMainBundle:User:login

login_check:
    path: /login_check

logout:
    path: /logout