main_default_home:
    path: /home
    defaults:
        _controller: TFMainBundle:Default:Home

main_default_contact:
    path: /contact
    defaults:
        _controller: TFMainBundle:Default:Contact

main_default_register:
    path: /register
    defaults:
        _controller: TFMainBundle:User:Register

main_hotel_add:
    path: /hotel/add
    defaults:
        _controller: TFMainBundle:Hotel:add
